#!/bin/bash

set -e

# make sure that packer is installed
rm -rf ~/.local/share/nvim/site/pack/packer/start/packer.nvim

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

cp -r nvim ~/.config/

# start and stop nvim to enable Packer
nvim --headless -c "q"

# start and stop headless to PackerSync
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# start and stop headless to PackerSync
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
